### ISSUE TITLE
HerokuのRailsサイト正常稼働中

### ISSUE THREAD

**Issue by a1738tm** [a1738tm/rails_project#1]
@takabatoshiki @autumnzest
HerokuのRailsサイトが正常に動くようになりましたのでお知らせ致します。
不具合の原因はHerokuコマンドの実行漏れでした。
トップページにListing Booksへのリンクを張ってあります（演習課題7-1）。

これで環境は整いましたので、あとは開発を頑張りましょう！

**Comment by ghost** [comment]
本日の授業ですが、仕事の関係で、授業開始の６時３０分までに入室が難しい状況です。７時前までには入れそうですが、私の到着が７時として進めてください。
アプリのアイディアですが、ユーザのログインと投稿を実装し、投稿を登録しそれを表示するというのは如何でしょうか？短い授業時間で上記を実装するのは難しいかな、、、。
何れにしてもお二人でお決めになったものに従います。
私は、ユーザ登録とログイン（ユーザ名、パスワード）の実装を事前に作成して授業に参加します。

**Comment by a1738tm** [comment]
時間の件は承知しましたが、プルリクの件はどう解釈して良いか悩みます。

何を作るかは決定に従うとの発言と、ログイン機能を作成されプルリクを送られていることが、どうも矛盾しているように感じますが...
つまり高場さんがどういう意図でプルリクされたのか私には分からなくて。話し合いの結果もしアプリにログイン機能が不要だったとしたら、このプルリク破棄して良いんですか？

せっかく作ってくださったので是非とも取り込みたいと思いますが、最終的に何を作るかは直接会って話し会うということでよろしいですかね。
お待ちしてます。

**Comment by ghost** [comment]
村上さん
本日の授業は、６時３０分には到着しそうにございません。みなさんのアプリ決定の時間、及び機能の実装のための時間で、ご迷惑をおかけすると思い、勝手ながら作成しました。お二人の話し合いの結果に従います。

2017年7月28日 14:10 murakami <notifications@github.com>:

**Comment by a1738tm** [comment]
到着時間の件は承知しましたので大丈夫です。
何を作るかは先に話し合っておきますが、高場さんが到着されるまでは決定保留にしておきます。
プルリクをマージするかどうかは何を作るか決定してからにしようと思います（とはいえエラーを解消しないとマージできない）。

**Comment by a1738tm** [comment]
高場さん
お疲れさまです。
張さんと二人で、何を作るか一応決めました。
簡単な概要と構成図を書いて、あとでアップします。
