### ISSUE TITLE
中華料理の参考資料

### ISSUE THREAD

**Issue by autumnzest** [a1738tm/rails_project#13]
口水鶏（こうしゅいじぃ）
凉拌黄瓜（りゃんばんほぁんぐあー）
皮蛋豆腐（ぴぃだんどうふ）
回鍋肉（ふいぐぉーろう）
辣白菜（らーばいつぁい）
青椒肉絲（ちんじゃおろうすー） 
蒜泥白肉（すぁんにーばいろう）
麻婆豆腐（まーぼーどうふ）
西紅柿炒鶏蛋（しーほんしーつぁおじぃだん）
魚香肉絲（ゆいしゃんろうすー）
魚香茄辣（ゆいしゃんちえず）
辣子鶏（らーずぅじぃ）
木須肉（むぅすーろう）
北京烤鸭（べいじんかおやー）
红烧肉（ほんしょうろう）
水煮魚（しゅいじゅうゆい）
酸辣湯（すぁんらーたん）
揚州炒飯（やんじょーつぁおふぁん）
蛋炒飯（だんつぁおふぁん）
担担面（だんだんみえん）
雲呑（わんたん） 叉焼麺（ちゃーしゅーめん） 焼売（しゅーまい） 湯麺（たんめん） 広東麺（かんとんめん） 回鍋肉（ほいこーろー） 辣白菜（らーぱーつぁい） 搾菜（ざーさい） 青椒肉絲（ちんじゃおろーすー） 棒々鶏（ばんばんじー） 蒜泥白肉（しゃんにーばいろう） 皮蛋豆腐（ぴーたんどーふ） 青江菜（ちんげんさい） 豆板醤（とうばんじゃん

**Comment by a1738tm** [comment]
ありがとう
