### ISSUE TITLE
bundle exec rake db:migrate

### ISSUE THREAD

**Issue by ghost** [a1738tm/rails_project#19]
$ rails g model result username:string score:integer
$ bundle exec rake db:migrate
上記を行なっているですが、rake aborted と怒られてうまくいかない状況です。
以前、scaffoldのdevise userを使って、githubにアップしましたが、それと同じ症状が出ています。
その時は、ローカル環境で動作してgithubでpushしましたら、conflictを起こしていました。
私の方から、dbに関わる実装を控えます。今後のプロジェクトスピードが落ちますので。
commitを一回は行う必要がありますので、db以外のところで簡易なものを一つ分担ください。
よろしくお願いいたします。

**Comment by a1738tm** [comment]
@takabatoshiki こちらで現象が再現するか確認してみます。

**Comment by a1738tm** [comment]
私のローカルでコマンド通りました。
高場さんが作業されている頃と同じタイミングで、私もbooksのscaffoldを削除したりしてましたので、もしかしたらそれが原因かもしれません。
まずmasterを最新の状態にしていただき、その上で一旦ローカルに出来てしまっているデータベースを削除して、まっさらな状態から構築してみてください。
私はそうしました。
```shell
$ bundle exec rake db:drop
$ createdb rails_project_development
$ createdb rails_project_test
```
上記の手順でまっさらなデータベースに戻ります。
ここから高場さんのコマンドを実行してください。
```shell
$ rails g model result username:string score:integer
$ bundle exec rake db:migrate
```
もしこれでも状況が改善されないようであれば、お手数ですが再度ここに書き込んでください。
