### ISSUE TITLE
bundle exec rake db:drop

### ISSUE THREAD

**Issue by ghost** [a1738tm/rails_project#21]
おそくなりました。
ローカル環境を行いました結果を共有します。
下添付の画像ファイルが見えないようでしたら、ご連絡ください。
<img width="810" alt="2017-08-04 9 32 31" src="https://user-images.githubusercontent.com/9856909/28949507-1f38e0c2-78f8-11e7-8816-6cd6322626a7.png">

**Comment by a1738tm** [comment]
出ているエラーはpgモジュールのバージョンが新しいことが原因ですが、実害はないので無視して進めてください。
