### ISSUE TITLE
Resultクラスに欲しい機能

### ISSUE THREAD

**Issue by a1738tm** [a1738tm/rails_project#24]
app/models/配下の Resultクラスに以下のメソッドを追加

スコアが何位に相当するのかを取得（スコアがDBに登録される前）
```
get_rank
    引数：スコア
    戻り値：順位
```

ユーザ名の重複チェック（重複していたらtrueを返す）
```
exists
    引数：ユーザ名
    戻り値：true / false
```

ランキング取得
戻り値のリストの内容は（rank, username, score）
rank: 順位（同一スコアの人が複数存在する場合を考慮する）
username: ユーザ名
score: スコア
```
get_ranking
    引数：なし
    戻り値：ランキングのリスト
```

**Comment by ghost** [comment]
上記の実装及びTravis CIの了解をもらえましたのでご確認ください。

**Comment by a1738tm** [comment]
夜遅くまで対応お疲れさまでした。
話がうまく伝わらない部分があったようで、いくつかはこちらの意図どおり動作しなかったのですが、
そのへんは、いったんmasterにマージした上で私のほうで調整（改修）させていただこうと思います。
ありがとうございました。
