### ISSUE TITLE
クイズの問題の作成

### ISSUE THREAD

**Issue by a1738tm** [a1738tm/rails_project#29]
@takabatoshiki @autumnzest 
おつかれさまです。
これが最後のタスクです。

クイズの問題を考えるときがきました。最低でも10問必要なので、ひとり最低3〜4問は考える必要があります。
思いついたクイズをここに書き込んでいってください。

テーマは、中華料理、中国文化、四字熟語、国名、首都名など。
問題や選択肢はなるべく文字数を減らしてください。
また、画像を使った問題は無しです（すべて文章問題）。

書式
```
[問題]
中華料理のバンバンジー。漢字で書くと？

[選択肢]
1.棒棒鶏
2.万飯爺
3.万々慈
4.飯々餌

[正解]
1
```

よろしくお願いします。

**Comment by autumnzest** [comment]
[問題]
中華料理の搾菜。読むと？

[選択肢]
1.ザーサイ
2.シボナ
3.シボサイ
4.シーサイ

[正解]
1

[問題]
中華料理のザーサイ。書くと？

[選択肢]
1.搾菜
2.在菜
3.再菜
4.差菜

[正解]
1

**Comment by a1738tm** [comment]
```
[問題]
四字熟語「◯人◯色」、◯の数を足すといくつ？

[選択肢]
1.5
2.10
3.15
4.20

[正解]
4


[問題]
最も緯度が低い都市はどこ？

[選択肢]
1.香港
2.那覇
3.上海
4.台北

[正解]
1
```

**Comment by autumnzest** [comment]
[問題]
「上洛」の「洛」はどこ？

[選択肢]
1.東京
2.京都
3.大阪
4.沖縄

[正解]
2

**Comment by ghost** [comment]
日本一小さな都道府県は？

① 香川県
② 島根県
③ 東京都
④ 沖縄県

答え：①香川県

**Comment by ghost** [comment]
第二次世界大戦で，日本に原子爆弾が落とされたときにアメリカの大統領を務めていたのは誰でしょう？
　１．トルーマン　　２．アイゼンハワー　
　３．ウィルソン　　４．Ｆ．ルーズベルト

答え：１のトルーマン

**Comment by autumnzest** [comment]
＿花繚乱

　１．一　　２. 十　
　３．百　　４. 千

答え：３

**Comment by ghost** [comment]
イエズス会の宣教師フランシスコ=ザビエルが日本に来たとき，最初に上陸した場所はどこでしょう？
　１．鹿児島　　２．長　崎　
　３．種子島　　４．根　室

答え：１の鹿児島

**Comment by autumnzest** [comment]
明鏡止＿

　１．木　　２. 石　
　３．水　　４. 心

答え：３

**Comment by ghost** [comment]
中国の人口はおよそ何億人？

1. ３億人
2. １０億人
3.  １３億人
4. ２３億人

答え：３の１３億人

**Comment by autumnzest** [comment]
＿撓＿屈

　１．一　　２. 不　
　３．大　　４.小 

答え：２

**Comment by ghost** [comment]
中国はいくつの民族が住んでいるでしょう？

1. １６
2. ３６
3. ５６
4. ７６

回答：３の５６

**Comment by autumnzest** [comment]
情けは【 ？ 】のためならず

　１．人　　２. 自分　
　３．世　　４. 悪

答え：１

**Comment by autumnzest** [comment]
【 ？ 】でも動かない

1. 金かね
2. 梃てこ
3. 意地いじ
4. 銃

答え：　２

**Comment by ghost** [comment]
中華料理でチンジャオロースーの「チンジャオ」とは何のこと？
1. 牛肉
2. 豚肉
3. ピーマン
4. 白菜

答え：3のピーマン

**Comment by autumnzest** [comment]
豹の読み方は？

　１．ひょう　　２. きょう　
　３．りょう　　４. しょう

答え：１

**Comment by ghost** [comment]
中華料理店の天津飯や中華丼が考案された国はどこ？
1. 中国
2. 韓国
3. 台湾
4. 日本

回答：４の日本

**Comment by autumnzest** [comment]
鼈の読み方は？

　１．ベイ　　２. ペイ　
　３．ベツ　　４. ペツ

答え：３

**Comment by autumnzest** [comment]
躑躅の読み方はどれ？

　１．ツツシ　　２. ツヅシ　
　３．ツツジ　　４. ヅヅシ

答え：３
