### ISSUE TITLE
Resultクラスの実装

### ISSUE THREAD

**Issue by ghost** [a1738tm/rails_project#31]
最終の実装宜しくお願いいします。お時間があるときで結構ですので、お知らせいただいたりリクエストと違った点はフィードバックください。

**Comment by a1738tm** [comment]
get_rankメソッドは正しく動きました。
正直、自分には思いつかないような複雑なコードだったので戸惑いましたが、
実際に動かしてみると正しい結果を返してくれていたので、このまま採用させていただきます。

exitsはメソッドとして、つまりget_rankなどと同様の形式で提供していただくことを期待してました。
説明するときに親クラスのexits?メソッドの話をしたので、それがかえって混乱させてしまったかもしれません。

get_rankingは、ひとつバグを見つけました。ソートされていません。
rubyにはsortとsort!があるらしく、配列の中身を直接ソートするときは「!」つきのsortを使うようです。
で、これ自体の修正は簡単なので問題なかったのですが、戻り値の形式が期待と食い違ってました。
配列は良いのですが、配列の中はハッシュ（辞書）形式が良かったです。ただこれは厳密に指定しなかった私が悪いです。

**Comment by ghost** [comment]
フィードバックありがとうございます。rankingはリストとあったので配列で返すことを考えました。ハッシュにご変更ください。sortは最終確認ができておらず申し訳ないです。exists?は正直、true/falseをどのように使うのかイメージがわかず、前回の授業時にdef check_usernameでreturn true/falseで示したのですが、貴殿の意図に沿うようなものではなかったと記憶してましたので、貴殿に改修してもらうことを前提に簡易実装しました。完成に向けて必要な改修よろしくお願いします。
