### ISSUE TITLE
作成するアプリの案

### ISSUE THREAD

**Issue by a1738tm** [a1738tm/rails_project#4]
@takabatoshiki @autumnzest
[rails_project.pdf](https://github.com/a1738tm/rails_project/files/1183312/rails_project.pdf)

役割分担は、希望があればお知らせください。
張さんがrubyよりもhtmlをやりたいそうなので、そのへん考慮します。

村上は残ったものを担当します。

**Comment by a1738tm** [comment]
ちなみに高場さんが作成されていたdeviseのscaffoldを見てみたのですが、すごく高機能だと思いますが、中で何をやっているのかほとんど分からないw
scaffoldは便利な反面、中でどんな処理をしているのか理解できなくなってしまうので、サンプルとして参考にしつつ、自分の手を動かして作ったほうが良いように思いました。

**Comment by autumnzest** [comment]
村上さん、pdfを作っていだだきましてありがとうございます。
