### ISSUE TITLE
画面の作成

### ISSUE THREAD

**Issue by a1738tm** [a1738tm/rails_project#8]
@autumnzest
おつかれさまです。
張さんに作っていただきたい画面は以下の４つです。pdfにいろいろ書いてしまったので誤解させてしまったかもしれませんが、とりあえず画面遷移図に書いてある４つの画面があれば良いです。
```
ユーザ登録画面  app/views/users/new.html.erb
クイズ画面      app/views/quizzes/show.html.erb
成績画面        app/views/results/show.html.erb
ランキング画面  app/views/rankings/show.html.erb
```
自分で新しいファイルを作らないで、上記のファイルを編集してください。ファイルを削除したり名前を変えるとアプリが動かなくなります。
あと、Railsの場合はbodyタグの中だけを書くようにしてください。headタグ等はRailsが自動的に付与します。

画面が作成できたらローカル環境で必ず動作確認をしてからpushしてください。
サーバを起動して以下のURLにアクセスすれば確認できます。
```
ユーザ登録画面  localhost:3000/
クイズ画面      localhost:3000/quiz
成績画面        localhost:3000/result
ランキング画面  localhost:3000/ranking
```
なお、画面の遷移やformのPOSTはまだ意識しなくて良いです。Railsで処理を書かないと動かないので。

それではよろしくお願いします。
次の授業までに完了する必要はないです。
時間があったらお願いします。

**Comment by a1738tm** [comment]
画面から変数を参照できるようにしました。
いま固定値になっている部分を変数に置き換える作業をお願いします。
詳細は授業のときに説明します。

/quiz
```
@quiz[:question] ... クイズの問題文
@quiz[:options][0] ... クイズの選択肢1
@quiz[:options][1] ... クイズの選択肢2
@quiz[:options][2] ... クイズの選択肢3
@quiz[:options][3] ... クイズの選択肢4
@quiz[:answer] ... クイズの正解番号（1〜4）
@number ... 問題番号（1〜10）
@username ... ユーザ名
```

/result
```
@score ... 得点
@total ... 全体人数
@rank ... 順位
@username ... ユーザ名
```

/ranking
```
@ranking[0..][:username] ... ユーザ名
@ranking[0..][:score] ... 得点
@username ... ユーザ名
```

**Comment by a1738tm** [comment]
いまクイズの結果（正解か不正解か）を表示する場所がないので、クイズ画面でボタンを押したときに、すぐにPOSTしないで、正解か不正解かをJavaScriptで判定して画面に表示する処理を追加したいと思っています。
詳細は授業のときに説明します。

**Comment by autumnzest** [comment]
了解です。

**Comment by a1738tm** [comment]
ありがとうございました。masterにマージしておきます。
これで画面の作業は一旦終了です。

クイズの問題を考えてもらいたいので、あとで連絡します。
