### ISSUE TITLE
pushするときのお願い事項

### ISSUE THREAD

**Issue by a1738tm** [a1738tm/rails_project#9]
@takabatoshiki @autumnzest
おつかれさまです。
ソースをpushするときにお願いがあります。

**1.pushする前にローカルで必ず動作確認してください**
編集した内容が正しく動作するか、pushする前に必ず確認をお願いします。動かないソースをpushすると他のメンバーに迷惑がかかります。

**2.他のメンバーが作成したファイルを編集・削除するときは必ず本人から承諾を得てください**
他のメンバーが作成したファイルを勝手に書き換えたり削除しないでください（追加はOK、ただし動作確認は必須）。
もし書き換えたり削除する場合は、プルリクエストを出して、マージする前にその人からレビュー（許可）を受けてください。

**3.pushしたらTravis CIのテスト結果を確認してください**
GitHubにpushすると自動的にTravis CIのテストが実行されます。テストには５分程度かかるようですが、必ず結果を確認して、テストが失敗していたら原因を調べて修正（再push）してください。
もし解決できなければ他のメンバーに相談してください。

**Comment by autumnzest** [comment]
わかりました。今度従ってやります。

**Comment by a1738tm** [comment]
Travis CIのテストを観察して、いつどういうタイミングでテストが実施されるのかが分かりました。
GitHubにpushして最終的にmasterにマージするまでの間に、合計３回のテストが走るようです。
具体的には以下のようです。

１回目 ブランチをGitHubにpushしたとき
２回目 ブランチをPull Requestしたとき
３回目 Pull Requestをmasterにマージしたとき

テストは１回あたり約５分かかりますので、単純計算で１５分もかかります。
また、Pull Requestをmasterにマージして直ぐにブランチを削除すると、Travis CIのテスト（３回目）がエラーになってしまうようです。
私は何度かやらかしました。
ここでエラーになるとHerokuに自動デプロイされなくなってしまいますので、ブランチの削除はテストが完了してからにしましょう。
